name: Testing Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        find . -name 'requirements.txt' -exec pip install -r {} \;
        
    - name: Install pytest-cov for coverage reporting
      run: pip install pytest-cov
    
    - name: Install pytest-asyncio
      run: pip install pytest-asyncio

    - name: Configure pytest.ini
      run: |
        if [ ! -f pytest.ini ]; then
          echo "[pytest]" > pytest.ini
        fi
        echo "asyncio_default_fixture_loop_scope = function" >> pytest.ini

    - name: Run pytest with coverage and save report to text file
      run: pytest --cov=. | tee coverage_report.txt

    - name: Upload coverage text report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-txt-report
        path: coverage_report.txt
